# Generated by Django 4.0.3 on 2022-03-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_alter_comment_date_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_comment',
            field=models.BooleanField(default=True, verbose_name='Published'),
        ),
    ]
